apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: lemp-ns
  labels:
    Deployment: lemp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: lemp-db
        image: mariadb:latest
        envFrom:
        - configMapRef:
            name: configmap-db
        volumeMounts:
        - name: volume-db
          mountPath: /var/lib/mysql
      volumes:
      - name: volume-db
        hostPath:
          path: /home/data/mysql
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/hostname: k8s-node1
