apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    Service: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: port-nginx
    port: 8080
    targetPort: 80
    nodePort: 3456
