apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lemp-ns
  labels:
    Deployment: lemp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: lemp-nginx
        image: registry.gitlab.com/qminhh/test/k8s-nginx:latest1 
        ports:
        - containerPort: 80
        volumeMounts:
        - name: volume-nginx
          mountPath: /var/www/html
      volumes:
      - name: volume-nginx
        hostPath:
          path: /src
