apiVersion: v1
kind: Service
metadata:
  name: phpfpm-service
  namespace: lemp-ns
  labels:
    service: phpfpm
spec:
  selector:
    app: phpfpm 
  type: NodePort
  ports:
  - name: port-nginx
    port: 9000
    targetPort: 9000
