apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm-deployment
  namespace: lemp-ns
  labels:
    Deployment: lemp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpfpm
  template:
    metadata:
      labels:
        app: phpfpm
    spec:
      containers:
      - name: lemp-phpfpm
        image: registry.gitlab.com/qminhh/test/k8s-test:php
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: volume-phpfpm
          mountPath: /var/www/html
      volumes:
      - name: volume-phpfpm
        hostPath:
          path: /src
